name: Build Image And Publish

on:
  # schedule:
  #   - cron: "0 0 * * *" # Запуск каждый день в 00:00
  push:
    branches: [ "production" ]
  workflow_dispatch:

jobs:

  build_and_pub:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ secrets.DOCKER_USERNAME }}/kerla2:latest
          push: true
          context: kerla2_server/
          platforms: linux/amd64,linux/arm64
          build-args:
            mode=staging


  trigger_deployment_webhook:

    needs: build_and_pub
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook for deploy
        run:  |
          curl --location ${{ secrets.DEPLOYMENT_SERVER_WEBHOOK_URL }} \
            --header 'Authorization: ${{ secrets.DEPLOYMENT_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{ "docker_image": "kerla2" }'
